version: '3.8'

services:
  mysql:
    image: mysql
    container_name: patients_mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patients_data
      MYSQL_USER: Adhi
      MYSQL_PASSWORD: Adhi@123
    volumes:
      - patients_data_mysql:/var/lib/mysql

  nodejs:
    build: ./server
    image: patients_app:v1
    container_name: patients_nodejs
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      DB_HOST: patients_mysql
      DB_USER: Adhi
      DB_PASSWORD: Adhi@123
      DB_NAME: patients_data
      DB_PORT: 3306
    depends_on:
      - mysql

volumes:
  patients_data_mysql:
    
